#CREATE DATABASE IF NOT EXISTS SUPER_APP DEFAULT CHARSET UTF8 COLLATE UTF8_GENERAL_CI ;

#USE SUPER_APP ;

DROP TABLE IF EXISTS TB_USER;

CREATE TABLE TB_USER (
  ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT '用户ID, 主键自增',
  USER_CODE VARCHAR (22) NOT NULL UNIQUE COMMENT '用户编码 16位：SYS+20190123115803创建日期14位+5位随机编码',
  LOGIN_NAME VARCHAR (50) NOT NULL UNIQUE COMMENT '登陆用户名',
  LOGIN_PASSWORD VARCHAR (50) NOT NULL COMMENT '登陆密码',
  REAL_NAME VARCHAR (20) NOT NULL COMMENT '真实姓名',
  USER_SEX CHAR NOT NULL DEFAULT '0' COMMENT '性别：0-男 1-女',
  EMAIL VARCHAR (100) NOT NULL UNIQUE COMMENT '电子邮件',
  CELL_PHONE VARCHAR (20) NOT NULL UNIQUE COMMENT '手机号码',
  ADDRESS VARCHAR (100) NOT NULL COMMENT '邮寄地址',
  USER_TYPE TINYINT UNSIGNED NOT NULL COMMENT '用户类型 1:系统用户 0:注册会员用户',
  USER_TAG VARCHAR(300) DEFAULT NULL COMMENT '个人签名',
  USER_HEAD VARCHAR(300) DEFAULT 'https://raw.githubusercontent.com/TommyLemon/StaticResources/master/APIJSON_Logo.png' COMMENT '头像url',
  CONTACTID_LIST json DEFAULT NULL COMMENT '联系人id列表',
  PICTURE_LIST json DEFAULT NULL COMMENT '相册照片列表',
  STATE TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态 1:可用状态  0:删除状态  2:锁定状态',
  CREATE_BY BIGINT UNSIGNED NOT NULL DEFAULT '1000' COMMENT '创建人ID',
  CREATE_DATE DATETIME NOT NULL DEFAULT NOW() COMMENT '创建时间',
  UPDATE_BY BIGINT UNSIGNED NOT NULL DEFAULT '1000' COMMENT '修改人ID',
  UPDATE_DATE DATETIME NOT NULL DEFAULT NOW() COMMENT '修改时间',
  PRIMARY KEY (ID),
  KEY IDX_USER_STATE (STATE),
  KEY IDX_USER_TYPE (USER_TYPE),
  KEY IDX_USER_CODE (USER_CODE)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 AUTO_INCREMENT = 1000 COMMENT='用户表';


CREATE TABLE TB_COMMENT (
  ID BIGINT NOT NULL COMMENT '唯一标识,评论ID',
  TO_ID BIGINT NOT NULL DEFAULT '0' COMMENT '被回复的ID',
  USER_ID BIGINT NOT NULL COMMENT '评论人ID',
  MOMENT_ID BIGINT NOT NULL COMMENT '动态ID',
  CREATE_DATE DATETIME NOT NULL DEFAULT NOW() COMMENT '创建时间',
  CONTENT VARCHAR(1000) NOT NULL COMMENT '内容',
  PRIMARY KEY (ID),
  KEY IDX_USER_ID (USER_ID),
  KEY IDX_MOMENT_ID (MOMENT_ID),
  KEY IDX_COMMENT_DATE (CREATE_DATE)
) ENGINE=INNODB DEFAULT CHARSET = UTF8 AUTO_INCREMENT = 1000 COMMENT='评论表';


CREATE TABLE TB_MOMENT (
  ID BIGINT NOT NULL COMMENT '唯一标识,动态ID',
  USER_ID BIGINT NOT NULL COMMENT '用户ID',
  CREATE_DATE DATETIME NOT NULL DEFAULT NOW() COMMENT '创建时间',
  CONTENT VARCHAR(300) DEFAULT NULL COMMENT '文字内容',
  PRAISE_USERID_LIST JSON NOT NULL COMMENT '点赞的用户ID列表',
  PICTURE_LIST JSON NOT NULL COMMENT '图片列表',
  PRIMARY KEY (ID),
  KEY IDX_MOMENT_USER_ID (USER_ID),
  KEY IDX_MOMENT_DATE (CREATE_DATE)
) ENGINE=INNODB DEFAULT CHARSET = UTF8 AUTO_INCREMENT = 1000 COMMENT='动态表';






