#CREATE DATABASE IF NOT EXISTS SUPER_APP DEFAULT CHARSET UTF8 COLLATE UTF8_GENERAL_CI ;

#USE SUPER_APP ;

DROP TABLE IF EXISTS TB_USER;

CREATE TABLE TB_USER (
  ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT '用户ID, 主键自增',
  USER_CODE VARCHAR (22) NOT NULL UNIQUE COMMENT '用户编码 16位：SYS+20190123115803创建日期14位+5位随机编码',
  LOGIN_NAME VARCHAR (50) NOT NULL UNIQUE COMMENT '登陆用户名',
  LOGIN_PASSWORD VARCHAR (50) NOT NULL COMMENT '登陆密码',
  REAL_NAME VARCHAR (20) NOT NULL COMMENT '真实姓名',
  USER_SEX CHAR NOT NULL DEFAULT '0' COMMENT '性别：0-男 1-女',
  EMAIL VARCHAR (100) NOT NULL UNIQUE COMMENT '电子邮件',
  CELL_PHONE VARCHAR (20) NOT NULL UNIQUE COMMENT '手机号码',
  ADDRESS VARCHAR (100) NOT NULL COMMENT '邮寄地址',
  USER_TYPE TINYINT UNSIGNED NOT NULL COMMENT '用户类型 1:系统用户 0:注册会员用户',
  IP_LIST JSON NOT NULL COMMENT '用户注册必须填写IP白名单',
  USER_TAG VARCHAR(300) DEFAULT NULL COMMENT '个人签名',
  USER_HEAD VARCHAR(300) DEFAULT 'https://raw.githubusercontent.com/TommyLemon/StaticResources/master/APIJSON_Logo.png' COMMENT '头像url',
  CONTACTID_LIST JSON DEFAULT NULL COMMENT '联系人id列表',
  PICTURE_LIST JSON DEFAULT NULL COMMENT '相册照片列表',
  STATE TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态 1:可用状态  0:删除状态  2:锁定状态',
  CREATE_BY BIGINT UNSIGNED NOT NULL DEFAULT '1000' COMMENT '创建人ID',
  CREATE_DATE DATETIME NOT NULL DEFAULT NOW() COMMENT '创建时间',
  UPDATE_BY BIGINT UNSIGNED NOT NULL DEFAULT '1000' COMMENT '修改人ID',
  UPDATE_DATE DATETIME NOT NULL DEFAULT NOW() COMMENT '修改时间',
  PRIMARY KEY (ID),
  KEY IDX_USER_STATE (STATE),
  KEY IDX_USER_TYPE (USER_TYPE),
  KEY IDX_USER_CODE (USER_CODE)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 AUTO_INCREMENT = 1000 COMMENT='用户表';

DROP TABLE IF EXISTS TB_COMMENT;

CREATE TABLE TB_COMMENT (
  ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT '唯一标识,评论ID',
  TO_ID BIGINT NOT NULL DEFAULT '0' COMMENT '被回复的ID',
  USER_ID BIGINT NOT NULL COMMENT '评论人ID',
  MOMENT_ID BIGINT NOT NULL COMMENT '动态ID',
  CREATE_DATE DATETIME NOT NULL DEFAULT NOW() COMMENT '创建时间',
  CONTENT VARCHAR(1000) NOT NULL COMMENT '内容',
  PRIMARY KEY (ID),
  KEY IDX_USER_ID (USER_ID),
  KEY IDX_MOMENT_ID (MOMENT_ID),
  KEY IDX_COMMENT_DATE (CREATE_DATE)
) ENGINE=INNODB DEFAULT CHARSET = UTF8 AUTO_INCREMENT = 1000 COMMENT='评论表';

DROP TABLE IF EXISTS TB_MOMENT;

CREATE TABLE TB_MOMENT (
  ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT '唯一标识,动态ID',
  USER_ID BIGINT NOT NULL COMMENT '用户ID',
  CREATE_DATE DATETIME NOT NULL DEFAULT NOW() COMMENT '创建时间',
  CONTENT VARCHAR(300) DEFAULT NULL COMMENT '文字内容',
  PRAISE_USERID_LIST JSON NOT NULL COMMENT '点赞的用户ID列表',
  PICTURE_LIST JSON NOT NULL COMMENT '图片列表',
  PRIMARY KEY (ID),
  KEY IDX_MOMENT_USER_ID (USER_ID),
  KEY IDX_MOMENT_DATE (CREATE_DATE)
) ENGINE=INNODB DEFAULT CHARSET = UTF8 AUTO_INCREMENT = 1000 COMMENT='动态表';

DROP TABLE IF EXISTS TB_PRODUCT;

CREATE TABLE TB_PRODUCT (
  PRO_ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT '商品ID',
  PRO_NAME VARCHAR (100) NOT NULL UNIQUE COMMENT '商品名称',
  PRO_REAL_PRICE DOUBLE (9, 2) UNSIGNED NOT NULL COMMENT '商品原价',
  PRO_NOW_PRICE DOUBLE (9, 2) UNSIGNED NOT NULL COMMENT '商品现价',
  IS_STOCK TINYINT UNSIGNED NOT NULL COMMENT '是否有库存 1：有库存 0：无库存',
  PRO_DESC VARCHAR (200) NOT NULL COMMENT '商品简述',
  PRO_SIZE VARCHAR (50) NOT NULL COMMENT '商品大小',
  PRO_COLOR VARCHAR (50) NOT NULL COMMENT '商品颜色',
  PRO_SCORE DOUBLE (2, 1) UNSIGNED NOT NULL COMMENT '评价分数',
  PRO_TYPE_ID BIGINT UNSIGNED NOT NULL COMMENT '商品类型ID',
  PRO_PIC_LIST JSON NOT NULL COMMENT '商品图片列表',
  STATE TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态 1:可用状态  0:删除状态',
  CREATE_BY BIGINT UNSIGNED NOT NULL DEFAULT '1000' COMMENT '创建人ID',
  CREATE_DATE DATETIME NOT NULL DEFAULT NOW() COMMENT '创建时间',
  UPDATE_BY BIGINT UNSIGNED NOT NULL DEFAULT '1000' COMMENT '修改人ID',
  UPDATE_DATE DATETIME NOT NULL DEFAULT NOW() COMMENT '修改时间',
  PRIMARY KEY (PRO_ID),
  KEY IDX_PRO_NAME (PRO_NAME),
  KEY IDX_PRO_STATE (STATE)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 AUTO_INCREMENT = 1000 COMMENT = '商品表' ;

DROP TABLE IF EXISTS TB_PRO_TYPE;

CREATE TABLE TB_PRO_TYPE (
  TYPE_ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT '商品类型ID',
  TYPE_NAME VARCHAR (50) NOT NULL COMMENT '商品类型名称',
  TYPE_P_ID BIGINT UNSIGNED NOT NULL COMMENT '商品类型父ID',
  STATE TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态 1:可用状态  0:删除状态',
  CREATE_BY BIGINT UNSIGNED NOT NULL DEFAULT '1000' COMMENT '创建人ID',
  CREATE_DATE DATETIME NOT NULL DEFAULT NOW() COMMENT '创建时间',
  UPDATE_BY BIGINT UNSIGNED NOT NULL DEFAULT '1000' COMMENT '修改人ID',
  UPDATE_DATE DATETIME NOT NULL DEFAULT NOW() COMMENT '修改时间',
  PRIMARY KEY (TYPE_ID),
  KEY IDX_TYPE_NAME (TYPE_NAME),
  KEY IDX_TYPE_P_ID (TYPE_P_ID),
  KEY IDX_TYPE_STATE (STATE)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 AUTO_INCREMENT = 1000 COMMENT = '商品类型表';

DROP TABLE IF EXISTS TB_SERVICE_GETWAY;

CREATE TABLE TB_SERVICE_GETWAY (
  ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT '服务ID',
  SERVICE_NAME VARCHAR (50) NOT NULL COMMENT '服务名称',
  SERVICE_VERSION VARCHAR (50) NOT NULL COMMENT '服务版本号',
  SERVICE_HAS_SEARCH TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '可查询状态 1:可查询 0:不能查询',
  SERVICE_HAS_FILE TINYINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否文件接口 1:是 0:否',
  SERVICE_PAGE_ABLE TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '是否分页 1:是 0:否',
  STATE TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态 1:可用状态  0:删除状态',
  CREATE_BY BIGINT UNSIGNED NOT NULL DEFAULT '1000' COMMENT '创建人ID',
  CREATE_DATE DATETIME NOT NULL DEFAULT NOW() COMMENT '创建时间',
  UPDATE_BY BIGINT UNSIGNED NOT NULL DEFAULT '1000' COMMENT '修改人ID',
  UPDATE_DATE DATETIME NOT NULL DEFAULT NOW() COMMENT '修改时间',
  PRIMARY KEY (ID),
  KEY IDX_SERVICE_NAME (SERVICE_NAME),
  KEY IDX_SERVICE_VERSION (SERVICE_VERSION),
  KEY IDX_TYPE_STATE (STATE)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 AUTO_INCREMENT = 1000 COMMENT = '服务网关表';




